name: model-wine-quality
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    container: docker://dvcorg/cml-py3:latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: iterative/setup-cml@v1
      - uses: actions/setup-python@v4
      - name: cml_run
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install --upgrade pip
          pip install -r requirements.txt
          python train.py
      - name: write CML report
        env:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
        run:
          echo "## Model Metrics" >> report.md 
          cat metrics.txt >> report.md
          cat metrics.txt
          cml comment create report.md
          
          # echo '## Data  Viz' >> report.md
          # echo "![](./feature_importance.png)" >> report.md
          # echo "![](./residuals.png)" >> report.md

          
      
