name: model-wine-quality
on: [push]
jobs:
  train-and-report:
    runs-on: ubuntu-latest
    container: docker://ghcr.io/iterative/cml:0-dvc2-base1
    steps:
      - uses: actions/checkout@v3
      - name: Train model
        env:
          REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Your ML workflow goes here
          pip install --upgrade pip
          pip install -r requirements.txt
          python train.py

          # Model Metrics 
          cat metrics.txt >> report.md
          
          # echo '## Data  Viz' >> report.md
          # echo '![](./feature_importance.png "Feature importance")' >> report.md
          # echo '![](./residuals.png "Residual Plot")' >> report.md
          cml comment create report.md

          
      
